import "../globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <script src="https://js.hcaptcha.com/1/api.js" async defer></script>
      <body>{children}</body>
    </html>
  )
}
